application/models.py
from application import db

# Quiz questions table
class Questions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_name = db.Column(db.Text, nullable=False)
    displayed = db.Column(db.Integer)
    #to link each option to its question
    options = db.relationship('Options', backref='questions', lazy=True)
    # to retrieve question from responses table
    response = db.relationship('Responses', backref='questions', lazy=True)
    def __repr__(self):
        return f"Questions('{self.question_name}')"


#Quiz options table
class Options(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    option_name = db.Column(db.String(20), nullable=False)
    correct_incorrect = db.Column(db.Integer)
    #to link each option to its question
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'),
                            nullable=False)
    #to retrieve the selected option from responses table
    response = db.relationship('Responses', backref='options', lazy=True)
    def __repr__(self):
        return f"Options('{self.option_name}')"

# Quiz responses table
class Responses(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'),
                            nullable=False)
    option_id = db.Column(db.Integer, db.ForeignKey('options.id'),
                            nullable=False)
    #takes whether the chosen option was correct or not from the options table
    correct_incorrect= db.Column(db.Integer)

application/__init__.py
# Initializes and ties everything together for the application
# where application is initialized
from flask import Flask
# To use Sass compiler
from flask_assets import Environment, Bundle
#sqlalchemy
from flask_sqlalchemy import SQLAlchemy
from application.config import Config
#creation of extension objects
db = SQLAlchemy()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    # imports all the 3 blueprints
    from application.main.routes import main
    from application.quiz.routes import Quiz
    from application.errors.handlers import errors
    app.register_blueprint(main)
    app.register_blueprint(Quiz)
    app.register_blueprint(errors)
    # extension objects applied to each application
    db.init_app(app)
    # setting up sass compiler
    assets     = Environment(app)
    assets.url = app.static_url_path
    scss       = Bundle('style.scss', filters='pyscss', output='all.css')
    assets.config['SECRET_KEY'] = 'secret!'
    assets.config['PYSCSS_LOAD_PATHS'] = assets.load_path
    assets.config['PYSCSS_STATIC_URL'] = assets.url
    assets.config['PYSCSS_STATIC_ROOT'] = assets.directory
    assets.config['PYSCSS_ASSETS_URL'] = assets.url
    assets.config['PYSCSS_ASSETS_ROOT'] = assets.directory
    assets.register('scss_all', scss)

    return app

application/main/routes.py
from flask import render_template, url_for, request, redirect, flash, Blueprint
from application.models import Questions, Responses
from application import db

main = Blueprint('main', __name__)

# main page
@main.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")


# start page 
@main.route("/start")
def start():
    # Clears the responses table for the next quiz
    db.session.query(Responses).delete()
    db.session.commit()

    # sets the displayed values for all the questions back to false
    question_count = Questions.query.count() + 1
    for i in range(1,question_count):
        question = Questions.query.get(i)
        question.displayed = 0
        db.session.commit()
    return render_template("start.html")

application/quiz/routes.py
from flask import Blueprint, render_template, url_for, request, redirect, jsonify, make_response
from application.models import Questions, Options, Responses
from application import db
import random
from sqlalchemy.sql import func

Quiz = Blueprint('Quiz', __name__)

# actual quiz page 
@Quiz.route("/quiz", methods=["GET", "POST"])
def quiz():
    # if page is accessed from start page, return the quiz page
    if request.method == "GET":
        return render_template("quiz.html")

    # if timer runs out, return the results page
    else:
        return redirect(url_for('Quiz.results'))


# Asynchronous queries for questions and options after button is clicked
@Quiz.route("/query", methods=["GET", "POST"])
def query():
    # number of questions
    question_count = Questions.query.count()
    # sends question to quiz page and retrieves the option
    if request.method == "POST":
        response = request.get_json()
        
        # updates the 'Responses' table with the question and option
        q = Questions.query.filter_by(question_name=response['question']).first()
        o = Options.query.filter_by(option_name=response['answer']).first()
        resp = Responses(question_id=q.id, option_id=o.id, correct_incorrect=o.correct_incorrect)
        db.session.add(resp)
        db.session.commit()
    
    # int to check if all questions have been answered already
    response_count = 0

    # Finds a question that has not yet been displayed
    index = random.randint(1,question_count)
    q = Questions.query.get(index)
    while q.displayed == 1:
        index = random.randint(1,question_count)
        q = Questions.query.get(index)
        response_count +=1
        # if all questions are answered, redirects to the results with JS
        if (response_count == question_count):
            req = {
                "response_count": response_count,
                "question_count": question_count
            }
            response = make_response(jsonify(req), 200)
            return response
    q.displayed = 1
    db.session.commit()

    # Randomely selects an incorrect option for the questiom
    o2 =  Options.query.filter_by(question_id=index, correct_incorrect=0).order_by(func.random()).first()
    # Selects the correct option for the question
    o1 = Options.query.filter_by(question_id=index, correct_incorrect=1).first()
    # random number to decide which button correct answer should be on
    btn_id = random.randint(0,1)
    req = {
        "question": q.question_name,
        "correct": o1.option_name,
        "wrong":o2.option_name,
        "id":btn_id,
        "response_count": response_count,
        "question_count": question_count
    }
    response = make_response(jsonify(req), 200)
    return response
    

   
@Quiz.route("/quiz/results")
def results():
    # displays the number of correct and incorrect answers
    total_correct = Responses.query.filter_by(correct_incorrect=1).count()
    total_incorrect = Responses.query.filter_by(correct_incorrect=0).count()

    return render_template("results.html", total_correct=total_correct, total_incorrect=total_incorrect)

@Quiz.route("/quiz/summary")
def summary():

    #Stores 'Responses' table in a list
    table = []

    #Each row in 'Responses' is stored in a 'row' dictionary
    row_count = Responses.query.count() + 1
    for i in range(1,row_count):
        response = Responses.query.get(i)
        row = {}
        row['index'] = i
        row['question'] = Questions.query.get(response.question_id).question_name
        row['user_answer'] = Options.query.get(response.option_id).option_name
        row['correct_answer'] = Options.query.filter_by(question_id=response.question_id, correct_incorrect=1).first().option_name
        table.append(row)
    return render_template("summary.html",table=table)

application/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Homepage
{% endblock %}

{% block main %}
<script src="{{ url_for('static', filename='home.js') }}"></script>
    <div class="heading">
        <h1 class="title">QUICKFIRE NBA QUIZ!</h1>
    </div>
    
    <form action="{{ url_for('main.start') }}">
        <button class="button">PLAY!</button>
    </form>
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% assets "scss_all" %}
    <link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
    {% endassets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bungee">
    <title>EPIC NBA QUIZ: {% block title %}{% endblock %}</title>
  </head>

  <body id="page-layout">
    <header>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
    </header>
    <main class="container-fluid py-5 text-center">
        {% block main %}{% endblock %}
    </main>
  </body>
</html>

application/templates/quiz.html
{% extends "layout.html" %}

{% block title %}
    Quiz
{% endblock %}

{% block main %}
<script src="{{ url_for('static', filename='quiz.js') }}"></script>
    <!--Timer will go here, after it runs out, auto redirect to /results-->
    <div class="heading title" id="timer">
        <h1></h1>
    </div>

    
    <!-- Displays the Question and the 2 options-->
    <div class="align">
        <table>
            <thead>
                <tr>
                    <!--Each time q is retrieved, it is updated in a new database for user -->
                    <th id="question" colspan="2" scope="col"></th>
                </tr>
            </thead>
        </table>
    </div>
    <form action="" method="">
        <!--Randomely assigns the correct option to any of the buttons-->              
        <td><button type="submit" class="button" name="response" id="left"value=""></button></td>
        <td><button type="submit" class="button" name="response" id="right"value=""></button></td>                    
    </form>
{% endblock %}

application/templates/results.html
{% extends "layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block main %}
    <script src="{{ url_for('static', filename='results-summary.js') }}"></script>

    <div class="heading">
        <h1>Your Results</h1>
    </div>
    
    <!--Results of the quiz-->
    <div class="align">
        <table>
            <thead>
                <tr>
                    <th>CORRECT</th>
                    <th>INCORRECT</th>
                </tr>
            </thead>
            <tbody>
                <td class="correct">{{total_correct}}</td>
                <td class="wrong">{{total_incorrect}}</td>
            </tbody>
        </table>
    </div>
    <!--User can navigate back to start page, or to summary page-->
    <form>
        <button type="submit" class="button" formaction="{{ url_for('main.start') }}">Restart</button>
        <button type="submit" class="button" formaction="{{ url_for('Quiz.summary') }}">See Quiz Summary</button>
    </form>
{% endblock %}

application/templates/start.html
{% extends "layout.html" %}

{% block title %}
    Start
{% endblock %}

{% block main %}
    <script src="{{ url_for('static', filename='start.js') }}"></script>
    <div class="heading">
        <h2> Complete as many questions as you can in 25 Seconds!</h2>
        <h2>Press start when you're ready!</h2>
    </div>
    
    <form action="{{ url_for('Quiz.quiz') }}" method="get">
        <button class="button">START!</button>
    </form>
{% endblock %}

application/templates/summary.html
{% extends "layout.html" %}

{% block title %}
    Quiz Summary
{% endblock %}

{% block main %}
    <script src="{{ url_for('static', filename='results-summary.js') }}"></script>
<!--Info from user's quiz database is retrieved and displayed as a table-->
    <table class="table" id="summary">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Question</th>
                <th scope="col">Your Response</th>
                <th scope="col">Correct Response</th>
            </tr>
        </thead>
        <tbody>
            {% for row in table %}
                {% if row.user_answer == row.correct_answer %}
                    <tr class="correct">
                        <td>{{ row.index }}</td>
                        <td>{{ row.question }}</td>
                        <td>{{ row.user_answer }}</td>
                        <td>{{ row.correct_answer }}</td>
                    </tr>
                {% else %}
                    <tr class="wrong">
                        <td>{{ row.index }}</td>
                        <td>{{ row.question }}</td>
                        <td>{{ row.user_answer }}</td>
                        <td>{{ row.correct_answer }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <form>
        <button type="submit" class="button" formaction="{{ url_for('main.start') }}">Restart</button>
        <button type="submit" class="button" formaction="{{ url_for('main.home') }}">Home</button>
    </form>
{% endblock %}